/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes', function() {
    it('should create an instance of TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes', function() {
      // uncomment below and update the code to test TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be.a(Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes);
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property actionParameters (base name: "actionParameters")', function() {
      // uncomment below and update the code to test the property actionParameters
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property conditions (base name: "conditions")', function() {
      // uncomment below and update the code to test the property conditions
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedBy (base name: "updatedBy")', function() {
      // uncomment below and update the code to test the property updatedBy
      //var instance = new Documentation.TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();
      //expect(instance).to.be();
    });

  });

}));
