/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.TodoCreatedByDataAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TodoCreatedByDataAttributes', function() {
    it('should create an instance of TodoCreatedByDataAttributes', function() {
      // uncomment below and update the code to test TodoCreatedByDataAttributes
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be.a(Documentation.TodoCreatedByDataAttributes);
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property resetPasswordToken (base name: "resetPasswordToken")', function() {
      // uncomment below and update the code to test the property resetPasswordToken
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property registrationToken (base name: "registrationToken")', function() {
      // uncomment below and update the code to test the property registrationToken
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property roles (base name: "roles")', function() {
      // uncomment below and update the code to test the property roles
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property blocked (base name: "blocked")', function() {
      // uncomment below and update the code to test the property blocked
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property preferedLanguage (base name: "preferedLanguage")', function() {
      // uncomment below and update the code to test the property preferedLanguage
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedBy (base name: "updatedBy")', function() {
      // uncomment below and update the code to test the property updatedBy
      //var instance = new Documentation.TodoCreatedByDataAttributes();
      //expect(instance).to.be();
    });

  });

}));
