/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.TodoRequestData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TodoRequestData', function() {
    it('should create an instance of TodoRequestData', function() {
      // uncomment below and update the code to test TodoRequestData
      //var instance = new Documentation.TodoRequestData();
      //expect(instance).to.be.a(Documentation.TodoRequestData);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new Documentation.TodoRequestData();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new Documentation.TodoRequestData();
      //expect(instance).to.be();
    });

    it('should have the property bolean (base name: "bolean")', function() {
      // uncomment below and update the code to test the property bolean
      //var instance = new Documentation.TodoRequestData();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new Documentation.TodoRequestData();
      //expect(instance).to.be();
    });

  });

}));
