/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.UploadIdPostRequestFileInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UploadIdPostRequestFileInfo', function() {
    it('should create an instance of UploadIdPostRequestFileInfo', function() {
      // uncomment below and update the code to test UploadIdPostRequestFileInfo
      //var instance = new Documentation.UploadIdPostRequestFileInfo();
      //expect(instance).to.be.a(Documentation.UploadIdPostRequestFileInfo);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Documentation.UploadIdPostRequestFileInfo();
      //expect(instance).to.be();
    });

    it('should have the property alternativeText (base name: "alternativeText")', function() {
      // uncomment below and update the code to test the property alternativeText
      //var instance = new Documentation.UploadIdPostRequestFileInfo();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instance = new Documentation.UploadIdPostRequestFileInfo();
      //expect(instance).to.be();
    });

  });

}));
