/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.UploadFile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UploadFile', function() {
    it('should create an instance of UploadFile', function() {
      // uncomment below and update the code to test UploadFile
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be.a(Documentation.UploadFile);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property alternativeText (base name: "alternativeText")', function() {
      // uncomment below and update the code to test the property alternativeText
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property formats (base name: "formats")', function() {
      // uncomment below and update the code to test the property formats
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property hash (base name: "hash")', function() {
      // uncomment below and update the code to test the property hash
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property ext (base name: "ext")', function() {
      // uncomment below and update the code to test the property ext
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property mime (base name: "mime")', function() {
      // uncomment below and update the code to test the property mime
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property previewUrl (base name: "previewUrl")', function() {
      // uncomment below and update the code to test the property previewUrl
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property provider (base name: "provider")', function() {
      // uncomment below and update the code to test the property provider
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property providerMetadata (base name: "provider_metadata")', function() {
      // uncomment below and update the code to test the property providerMetadata
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Documentation.UploadFile();
      //expect(instance).to.be();
    });

  });

}));
