/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthChangePasswordPostRequest model module.
 * @module model/AuthChangePasswordPostRequest
 * @version 1.0.0
 */
class AuthChangePasswordPostRequest {
    /**
     * Constructs a new <code>AuthChangePasswordPostRequest</code>.
     * @alias module:model/AuthChangePasswordPostRequest
     * @param password {String} 
     * @param currentPassword {String} 
     * @param passwordConfirmation {String} 
     */
    constructor(password, currentPassword, passwordConfirmation) { 
        
        AuthChangePasswordPostRequest.initialize(this, password, currentPassword, passwordConfirmation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, currentPassword, passwordConfirmation) { 
        obj['password'] = password;
        obj['currentPassword'] = currentPassword;
        obj['passwordConfirmation'] = passwordConfirmation;
    }

    /**
     * Constructs a <code>AuthChangePasswordPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthChangePasswordPostRequest} obj Optional instance to populate.
     * @return {module:model/AuthChangePasswordPostRequest} The populated <code>AuthChangePasswordPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthChangePasswordPostRequest();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('currentPassword')) {
                obj['currentPassword'] = ApiClient.convertToType(data['currentPassword'], 'String');
            }
            if (data.hasOwnProperty('passwordConfirmation')) {
                obj['passwordConfirmation'] = ApiClient.convertToType(data['passwordConfirmation'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthChangePasswordPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthChangePasswordPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthChangePasswordPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['currentPassword'] && !(typeof data['currentPassword'] === 'string' || data['currentPassword'] instanceof String)) {
            throw new Error("Expected the field `currentPassword` to be a primitive type in the JSON string but got " + data['currentPassword']);
        }
        // ensure the json data is a string
        if (data['passwordConfirmation'] && !(typeof data['passwordConfirmation'] === 'string' || data['passwordConfirmation'] instanceof String)) {
            throw new Error("Expected the field `passwordConfirmation` to be a primitive type in the JSON string but got " + data['passwordConfirmation']);
        }

        return true;
    }


}

AuthChangePasswordPostRequest.RequiredProperties = ["password", "currentPassword", "passwordConfirmation"];

/**
 * @member {String} password
 */
AuthChangePasswordPostRequest.prototype['password'] = undefined;

/**
 * @member {String} currentPassword
 */
AuthChangePasswordPostRequest.prototype['currentPassword'] = undefined;

/**
 * @member {String} passwordConfirmation
 */
AuthChangePasswordPostRequest.prototype['passwordConfirmation'] = undefined;






export default AuthChangePasswordPostRequest;

