/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthSendEmailConfirmationPost200Response model module.
 * @module model/AuthSendEmailConfirmationPost200Response
 * @version 1.0.0
 */
class AuthSendEmailConfirmationPost200Response {
    /**
     * Constructs a new <code>AuthSendEmailConfirmationPost200Response</code>.
     * @alias module:model/AuthSendEmailConfirmationPost200Response
     */
    constructor() { 
        
        AuthSendEmailConfirmationPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthSendEmailConfirmationPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthSendEmailConfirmationPost200Response} obj Optional instance to populate.
     * @return {module:model/AuthSendEmailConfirmationPost200Response} The populated <code>AuthSendEmailConfirmationPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthSendEmailConfirmationPost200Response();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('sent')) {
                obj['sent'] = ApiClient.convertToType(data['sent'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthSendEmailConfirmationPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthSendEmailConfirmationPost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['sent'] && !(typeof data['sent'] === 'string' || data['sent'] instanceof String)) {
            throw new Error("Expected the field `sent` to be a primitive type in the JSON string but got " + data['sent']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
AuthSendEmailConfirmationPost200Response.prototype['email'] = undefined;

/**
 * @member {module:model/AuthSendEmailConfirmationPost200Response.SentEnum} sent
 */
AuthSendEmailConfirmationPost200Response.prototype['sent'] = undefined;





/**
 * Allowed values for the <code>sent</code> property.
 * @enum {String}
 * @readonly
 */
AuthSendEmailConfirmationPost200Response['SentEnum'] = {

    /**
     * value: "true"
     * @const
     */
    "true": "true"
};



export default AuthSendEmailConfirmationPost200Response;

