/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthResetPasswordPostRequest model module.
 * @module model/AuthResetPasswordPostRequest
 * @version 1.0.0
 */
class AuthResetPasswordPostRequest {
    /**
     * Constructs a new <code>AuthResetPasswordPostRequest</code>.
     * @alias module:model/AuthResetPasswordPostRequest
     */
    constructor() { 
        
        AuthResetPasswordPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthResetPasswordPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthResetPasswordPostRequest} obj Optional instance to populate.
     * @return {module:model/AuthResetPasswordPostRequest} The populated <code>AuthResetPasswordPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResetPasswordPostRequest();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('passwordConfirmation')) {
                obj['passwordConfirmation'] = ApiClient.convertToType(data['passwordConfirmation'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthResetPasswordPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthResetPasswordPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['passwordConfirmation'] && !(typeof data['passwordConfirmation'] === 'string' || data['passwordConfirmation'] instanceof String)) {
            throw new Error("Expected the field `passwordConfirmation` to be a primitive type in the JSON string but got " + data['passwordConfirmation']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}



/**
 * @member {String} password
 */
AuthResetPasswordPostRequest.prototype['password'] = undefined;

/**
 * @member {String} passwordConfirmation
 */
AuthResetPasswordPostRequest.prototype['passwordConfirmation'] = undefined;

/**
 * @member {String} code
 */
AuthResetPasswordPostRequest.prototype['code'] = undefined;






export default AuthResetPasswordPostRequest;

