/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthForgotPasswordPost200Response model module.
 * @module model/AuthForgotPasswordPost200Response
 * @version 1.0.0
 */
class AuthForgotPasswordPost200Response {
    /**
     * Constructs a new <code>AuthForgotPasswordPost200Response</code>.
     * @alias module:model/AuthForgotPasswordPost200Response
     */
    constructor() { 
        
        AuthForgotPasswordPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthForgotPasswordPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthForgotPasswordPost200Response} obj Optional instance to populate.
     * @return {module:model/AuthForgotPasswordPost200Response} The populated <code>AuthForgotPasswordPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthForgotPasswordPost200Response();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthForgotPasswordPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthForgotPasswordPost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ok'] && !(typeof data['ok'] === 'string' || data['ok'] instanceof String)) {
            throw new Error("Expected the field `ok` to be a primitive type in the JSON string but got " + data['ok']);
        }

        return true;
    }


}



/**
 * @member {module:model/AuthForgotPasswordPost200Response.OkEnum} ok
 */
AuthForgotPasswordPost200Response.prototype['ok'] = undefined;





/**
 * Allowed values for the <code>ok</code> property.
 * @enum {String}
 * @readonly
 */
AuthForgotPasswordPost200Response['OkEnum'] = {

    /**
     * value: "true"
     * @const
     */
    "true": "true"
};



export default AuthForgotPasswordPost200Response;

