/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ErrorData model module.
 * @module model/ErrorData
 * @version 1.0.0
 */
class ErrorData {
    /**
     * Constructs a new <code>ErrorData</code>.
     * @alias module:model/ErrorData
     * @param {(module:model/Object|module:model/[Object])} instance The actual instance to initialize ErrorData.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [Object]
            errorMessages.push("Failed to construct [Object]: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ErrorData` with oneOf schemas Object, [Object]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ErrorData` with oneOf schemas Object, [Object]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ErrorData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorData} obj Optional instance to populate.
     * @return {module:model/ErrorData} The populated <code>ErrorData</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ErrorData(data);
    }

    /**
     * Gets the actual instance, which can be <code>Object</code>, <code>[Object]</code>.
     * @return {(module:model/Object|module:model/[Object])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Object</code>, <code>[Object]</code>.
     * @param {(module:model/Object|module:model/[Object])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ErrorData.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ErrorData from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ErrorData} An instance of ErrorData.
     */
    static fromJSON = function(json_string){
        return ErrorData.constructFromObject(JSON.parse(json_string));
    }
}


ErrorData.OneOf = ["Object", "[Object]"];

export default ErrorData;

