/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributesRoles from './TodoCreatedByDataAttributesRoles';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';

/**
 * The TodoCreatedByDataAttributes model module.
 * @module model/TodoCreatedByDataAttributes
 * @version 1.0.0
 */
class TodoCreatedByDataAttributes {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributes</code>.
     * @alias module:model/TodoCreatedByDataAttributes
     */
    constructor() { 
        
        TodoCreatedByDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributes} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributes} The populated <code>TodoCreatedByDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributes();

            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('resetPasswordToken')) {
                obj['resetPasswordToken'] = ApiClient.convertToType(data['resetPasswordToken'], 'String');
            }
            if (data.hasOwnProperty('registrationToken')) {
                obj['registrationToken'] = ApiClient.convertToType(data['registrationToken'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = TodoCreatedByDataAttributesRoles.constructFromObject(data['roles']);
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
            if (data.hasOwnProperty('preferedLanguage')) {
                obj['preferedLanguage'] = ApiClient.convertToType(data['preferedLanguage'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['createdBy']);
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['updatedBy']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firstname'] && !(typeof data['firstname'] === 'string' || data['firstname'] instanceof String)) {
            throw new Error("Expected the field `firstname` to be a primitive type in the JSON string but got " + data['firstname']);
        }
        // ensure the json data is a string
        if (data['lastname'] && !(typeof data['lastname'] === 'string' || data['lastname'] instanceof String)) {
            throw new Error("Expected the field `lastname` to be a primitive type in the JSON string but got " + data['lastname']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['resetPasswordToken'] && !(typeof data['resetPasswordToken'] === 'string' || data['resetPasswordToken'] instanceof String)) {
            throw new Error("Expected the field `resetPasswordToken` to be a primitive type in the JSON string but got " + data['resetPasswordToken']);
        }
        // ensure the json data is a string
        if (data['registrationToken'] && !(typeof data['registrationToken'] === 'string' || data['registrationToken'] instanceof String)) {
            throw new Error("Expected the field `registrationToken` to be a primitive type in the JSON string but got " + data['registrationToken']);
        }
        // validate the optional field `roles`
        if (data['roles']) { // data not null
          TodoCreatedByDataAttributesRoles.validateJSON(data['roles']);
        }
        // ensure the json data is a string
        if (data['preferedLanguage'] && !(typeof data['preferedLanguage'] === 'string' || data['preferedLanguage'] instanceof String)) {
            throw new Error("Expected the field `preferedLanguage` to be a primitive type in the JSON string but got " + data['preferedLanguage']);
        }
        // validate the optional field `createdBy`
        if (data['createdBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['createdBy']);
        }
        // validate the optional field `updatedBy`
        if (data['updatedBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['updatedBy']);
        }

        return true;
    }


}



/**
 * @member {String} firstname
 */
TodoCreatedByDataAttributes.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
TodoCreatedByDataAttributes.prototype['lastname'] = undefined;

/**
 * @member {String} username
 */
TodoCreatedByDataAttributes.prototype['username'] = undefined;

/**
 * @member {String} email
 */
TodoCreatedByDataAttributes.prototype['email'] = undefined;

/**
 * @member {String} resetPasswordToken
 */
TodoCreatedByDataAttributes.prototype['resetPasswordToken'] = undefined;

/**
 * @member {String} registrationToken
 */
TodoCreatedByDataAttributes.prototype['registrationToken'] = undefined;

/**
 * @member {Boolean} isActive
 */
TodoCreatedByDataAttributes.prototype['isActive'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRoles} roles
 */
TodoCreatedByDataAttributes.prototype['roles'] = undefined;

/**
 * @member {Boolean} blocked
 */
TodoCreatedByDataAttributes.prototype['blocked'] = undefined;

/**
 * @member {String} preferedLanguage
 */
TodoCreatedByDataAttributes.prototype['preferedLanguage'] = undefined;

/**
 * @member {Date} createdAt
 */
TodoCreatedByDataAttributes.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
TodoCreatedByDataAttributes.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} createdBy
 */
TodoCreatedByDataAttributes.prototype['createdBy'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} updatedBy
 */
TodoCreatedByDataAttributes.prototype['updatedBy'] = undefined;






export default TodoCreatedByDataAttributes;

