/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoResponseDataObject from './TodoResponseDataObject';

/**
 * The TodoResponse model module.
 * @module model/TodoResponse
 * @version 1.0.0
 */
class TodoResponse {
    /**
     * Constructs a new <code>TodoResponse</code>.
     * @alias module:model/TodoResponse
     */
    constructor() { 
        
        TodoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoResponse} obj Optional instance to populate.
     * @return {module:model/TodoResponse} The populated <code>TodoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = TodoResponseDataObject.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          TodoResponseDataObject.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/TodoResponseDataObject} data
 */
TodoResponse.prototype['data'] = undefined;

/**
 * @member {Object} meta
 */
TodoResponse.prototype['meta'] = undefined;






export default TodoResponse;

