/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner model module.
 * @module model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner
 * @version 1.0.0
 */
class TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner</code>.
     * @alias module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner
     */
    constructor() { 
        
        TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner} The populated <code>TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner.prototype['id'] = undefined;

/**
 * @member {Object} attributes
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner.prototype['attributes'] = undefined;






export default TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner;

