/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoRequestData from './TodoRequestData';

/**
 * The TodoRequest model module.
 * @module model/TodoRequest
 * @version 1.0.0
 */
class TodoRequest {
    /**
     * Constructs a new <code>TodoRequest</code>.
     * @alias module:model/TodoRequest
     * @param data {module:model/TodoRequestData} 
     */
    constructor(data) { 
        
        TodoRequest.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>TodoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoRequest} obj Optional instance to populate.
     * @return {module:model/TodoRequest} The populated <code>TodoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoRequest();

            if (data.hasOwnProperty('data')) {
                obj['data'] = TodoRequestData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TodoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          TodoRequestData.validateJSON(data['data']);
        }

        return true;
    }


}

TodoRequest.RequiredProperties = ["data"];

/**
 * @member {module:model/TodoRequestData} data
 */
TodoRequest.prototype['data'] = undefined;






export default TodoRequest;

