/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';

/**
 * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes model module.
 * @module model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
 * @version 1.0.0
 */
class TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes</code>.
     * @alias module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    constructor() { 
        
        TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes} The populated <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('actionParameters')) {
                obj['actionParameters'] = ApiClient.convertToType(data['actionParameters'], Object);
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], Object);
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], Object);
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['createdBy']);
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['updatedBy']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // validate the optional field `role`
        if (data['role']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['role']);
        }
        // validate the optional field `createdBy`
        if (data['createdBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['createdBy']);
        }
        // validate the optional field `updatedBy`
        if (data['updatedBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['updatedBy']);
        }

        return true;
    }


}



/**
 * @member {String} action
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['action'] = undefined;

/**
 * @member {Object} actionParameters
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['actionParameters'] = undefined;

/**
 * @member {String} subject
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['subject'] = undefined;

/**
 * @member {Object} properties
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['properties'] = undefined;

/**
 * @member {Object} conditions
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['conditions'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} role
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['role'] = undefined;

/**
 * @member {Date} createdAt
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} createdBy
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['createdBy'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} updatedBy
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes.prototype['updatedBy'] = undefined;






export default TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes;

