/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoListResponseMetaPagination from './TodoListResponseMetaPagination';

/**
 * The TodoListResponseMeta model module.
 * @module model/TodoListResponseMeta
 * @version 1.0.0
 */
class TodoListResponseMeta {
    /**
     * Constructs a new <code>TodoListResponseMeta</code>.
     * @alias module:model/TodoListResponseMeta
     */
    constructor() { 
        
        TodoListResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoListResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoListResponseMeta} obj Optional instance to populate.
     * @return {module:model/TodoListResponseMeta} The populated <code>TodoListResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoListResponseMeta();

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = TodoListResponseMetaPagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoListResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoListResponseMeta</code>.
     */
    static validateJSON(data) {
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          TodoListResponseMetaPagination.validateJSON(data['pagination']);
        }

        return true;
    }


}



/**
 * @member {module:model/TodoListResponseMetaPagination} pagination
 */
TodoListResponseMeta.prototype['pagination'] = undefined;






export default TodoListResponseMeta;

