/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByData from './TodoCreatedByData';

/**
 * The TodoCreatedBy model module.
 * @module model/TodoCreatedBy
 * @version 1.0.0
 */
class TodoCreatedBy {
    /**
     * Constructs a new <code>TodoCreatedBy</code>.
     * @alias module:model/TodoCreatedBy
     */
    constructor() { 
        
        TodoCreatedBy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedBy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedBy} obj Optional instance to populate.
     * @return {module:model/TodoCreatedBy} The populated <code>TodoCreatedBy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedBy();

            if (data.hasOwnProperty('data')) {
                obj['data'] = TodoCreatedByData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedBy</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedBy</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          TodoCreatedByData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/TodoCreatedByData} data
 */
TodoCreatedBy.prototype['data'] = undefined;






export default TodoCreatedBy;

