/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner';

/**
 * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions model module.
 * @module model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions
 * @version 1.0.0
 */
class TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions</code>.
     * @alias module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions
     */
    constructor() { 
        
        TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions} The populated <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner>} data
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions.prototype['data'] = undefined;






export default TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions;

