/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';
import TodoCreatedByDataAttributesRolesDataInnerAttributesUsers from './TodoCreatedByDataAttributesRolesDataInnerAttributesUsers';

/**
 * The TodoCreatedByDataAttributesRolesDataInnerAttributes model module.
 * @module model/TodoCreatedByDataAttributesRolesDataInnerAttributes
 * @version 1.0.0
 */
class TodoCreatedByDataAttributesRolesDataInnerAttributes {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributesRolesDataInnerAttributes</code>.
     * @alias module:model/TodoCreatedByDataAttributesRolesDataInnerAttributes
     */
    constructor() { 
        
        TodoCreatedByDataAttributesRolesDataInnerAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributesRolesDataInnerAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributes} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributes} The populated <code>TodoCreatedByDataAttributesRolesDataInnerAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributesRolesDataInnerAttributes();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = TodoCreatedByDataAttributesRolesDataInnerAttributesUsers.constructFromObject(data['users']);
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions.constructFromObject(data['permissions']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['createdBy']);
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['updatedBy']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `users`
        if (data['users']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesUsers.validateJSON(data['users']);
        }
        // validate the optional field `permissions`
        if (data['permissions']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions.validateJSON(data['permissions']);
        }
        // validate the optional field `createdBy`
        if (data['createdBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['createdBy']);
        }
        // validate the optional field `updatedBy`
        if (data['updatedBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['updatedBy']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['name'] = undefined;

/**
 * @member {String} code
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['code'] = undefined;

/**
 * @member {String} description
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['description'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsers} users
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['users'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions} permissions
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['permissions'] = undefined;

/**
 * @member {Date} createdAt
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} createdBy
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['createdBy'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} updatedBy
 */
TodoCreatedByDataAttributesRolesDataInnerAttributes.prototype['updatedBy'] = undefined;






export default TodoCreatedByDataAttributesRolesDataInnerAttributes;

