/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributes from './TodoCreatedByDataAttributes';

/**
 * The TodoCreatedByData model module.
 * @module model/TodoCreatedByData
 * @version 1.0.0
 */
class TodoCreatedByData {
    /**
     * Constructs a new <code>TodoCreatedByData</code>.
     * @alias module:model/TodoCreatedByData
     */
    constructor() { 
        
        TodoCreatedByData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByData} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByData} The populated <code>TodoCreatedByData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = TodoCreatedByDataAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          TodoCreatedByDataAttributes.validateJSON(data['attributes']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TodoCreatedByData.prototype['id'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributes} attributes
 */
TodoCreatedByData.prototype['attributes'] = undefined;






export default TodoCreatedByData;

