/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner from './TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner';

/**
 * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole model module.
 * @module model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole
 * @version 1.0.0
 */
class TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole {
    /**
     * Constructs a new <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole</code>.
     * @alias module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole
     */
    constructor() { 
        
        TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} obj Optional instance to populate.
     * @return {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} The populated <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole();

            if (data.hasOwnProperty('data')) {
                obj['data'] = TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner} data
 */
TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.prototype['data'] = undefined;






export default TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole;

