/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TodoCreatedBy from './TodoCreatedBy';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole from './TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';

/**
 * The Todo model module.
 * @module model/Todo
 * @version 1.0.0
 */
class Todo {
    /**
     * Constructs a new <code>Todo</code>.
     * @alias module:model/Todo
     */
    constructor() { 
        
        Todo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Todo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Todo} obj Optional instance to populate.
     * @return {module:model/Todo} The populated <code>Todo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Todo();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('bolean')) {
                obj['bolean'] = ApiClient.convertToType(data['bolean'], 'Boolean');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('publishedAt')) {
                obj['publishedAt'] = ApiClient.convertToType(data['publishedAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = TodoCreatedBy.constructFromObject(data['createdBy']);
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.constructFromObject(data['updatedBy']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Todo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Todo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // validate the optional field `createdBy`
        if (data['createdBy']) { // data not null
          TodoCreatedBy.validateJSON(data['createdBy']);
        }
        // validate the optional field `updatedBy`
        if (data['updatedBy']) { // data not null
          TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole.validateJSON(data['updatedBy']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
Todo.prototype['title'] = undefined;

/**
 * @member {String} text
 */
Todo.prototype['text'] = undefined;

/**
 * @member {Boolean} bolean
 */
Todo.prototype['bolean'] = undefined;

/**
 * @member {Date} date
 */
Todo.prototype['date'] = undefined;

/**
 * @member {Date} createdAt
 */
Todo.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
Todo.prototype['updatedAt'] = undefined;

/**
 * @member {Date} publishedAt
 */
Todo.prototype['publishedAt'] = undefined;

/**
 * @member {module:model/TodoCreatedBy} createdBy
 */
Todo.prototype['createdBy'] = undefined;

/**
 * @member {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole} updatedBy
 */
Todo.prototype['updatedBy'] = undefined;






export default Todo;

