/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TodoListResponseMetaPagination model module.
 * @module model/TodoListResponseMetaPagination
 * @version 1.0.0
 */
class TodoListResponseMetaPagination {
    /**
     * Constructs a new <code>TodoListResponseMetaPagination</code>.
     * @alias module:model/TodoListResponseMetaPagination
     */
    constructor() { 
        
        TodoListResponseMetaPagination.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TodoListResponseMetaPagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TodoListResponseMetaPagination} obj Optional instance to populate.
     * @return {module:model/TodoListResponseMetaPagination} The populated <code>TodoListResponseMetaPagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TodoListResponseMetaPagination();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('pageCount')) {
                obj['pageCount'] = ApiClient.convertToType(data['pageCount'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TodoListResponseMetaPagination</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TodoListResponseMetaPagination</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} page
 */
TodoListResponseMetaPagination.prototype['page'] = undefined;

/**
 * @member {Number} pageSize
 */
TodoListResponseMetaPagination.prototype['pageSize'] = undefined;

/**
 * @member {Number} pageCount
 */
TodoListResponseMetaPagination.prototype['pageCount'] = undefined;

/**
 * @member {Number} total
 */
TodoListResponseMetaPagination.prototype['total'] = undefined;






export default TodoListResponseMetaPagination;

