/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadIdPostRequestFileInfo model module.
 * @module model/UploadIdPostRequestFileInfo
 * @version 1.0.0
 */
class UploadIdPostRequestFileInfo {
    /**
     * Constructs a new <code>UploadIdPostRequestFileInfo</code>.
     * @alias module:model/UploadIdPostRequestFileInfo
     */
    constructor() { 
        
        UploadIdPostRequestFileInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UploadIdPostRequestFileInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UploadIdPostRequestFileInfo} obj Optional instance to populate.
     * @return {module:model/UploadIdPostRequestFileInfo} The populated <code>UploadIdPostRequestFileInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadIdPostRequestFileInfo();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('alternativeText')) {
                obj['alternativeText'] = ApiClient.convertToType(data['alternativeText'], 'String');
            }
            if (data.hasOwnProperty('caption')) {
                obj['caption'] = ApiClient.convertToType(data['caption'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UploadIdPostRequestFileInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UploadIdPostRequestFileInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['alternativeText'] && !(typeof data['alternativeText'] === 'string' || data['alternativeText'] instanceof String)) {
            throw new Error("Expected the field `alternativeText` to be a primitive type in the JSON string but got " + data['alternativeText']);
        }
        // ensure the json data is a string
        if (data['caption'] && !(typeof data['caption'] === 'string' || data['caption'] instanceof String)) {
            throw new Error("Expected the field `caption` to be a primitive type in the JSON string but got " + data['caption']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
UploadIdPostRequestFileInfo.prototype['name'] = undefined;

/**
 * @member {String} alternativeText
 */
UploadIdPostRequestFileInfo.prototype['alternativeText'] = undefined;

/**
 * @member {String} caption
 */
UploadIdPostRequestFileInfo.prototype['caption'] = undefined;






export default UploadIdPostRequestFileInfo;

