/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsRole from './UsersPermissionsRole';

/**
 * The UsersPermissionsRolesGet200ResponseRolesInner model module.
 * @module model/UsersPermissionsRolesGet200ResponseRolesInner
 * @version 1.0.0
 */
class UsersPermissionsRolesGet200ResponseRolesInner {
    /**
     * Constructs a new <code>UsersPermissionsRolesGet200ResponseRolesInner</code>.
     * @alias module:model/UsersPermissionsRolesGet200ResponseRolesInner
     * @implements module:model/UsersPermissionsRole
     */
    constructor() { 
        UsersPermissionsRole.initialize(this);
        UsersPermissionsRolesGet200ResponseRolesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsRolesGet200ResponseRolesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsRolesGet200ResponseRolesInner} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsRolesGet200ResponseRolesInner} The populated <code>UsersPermissionsRolesGet200ResponseRolesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsRolesGet200ResponseRolesInner();
            UsersPermissionsRole.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('nb_users')) {
                obj['nb_users'] = ApiClient.convertToType(data['nb_users'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsRolesGet200ResponseRolesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsRolesGet200ResponseRolesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['description'] = undefined;

/**
 * @member {String} type
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['type'] = undefined;

/**
 * @member {Date} createdAt
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['updatedAt'] = undefined;

/**
 * @member {Number} nb_users
 */
UsersPermissionsRolesGet200ResponseRolesInner.prototype['nb_users'] = undefined;


// Implement UsersPermissionsRole interface:
/**
 * @member {Number} id
 */
UsersPermissionsRole.prototype['id'] = undefined;
/**
 * @member {String} name
 */
UsersPermissionsRole.prototype['name'] = undefined;
/**
 * @member {String} description
 */
UsersPermissionsRole.prototype['description'] = undefined;
/**
 * @member {String} type
 */
UsersPermissionsRole.prototype['type'] = undefined;
/**
 * @member {Date} createdAt
 */
UsersPermissionsRole.prototype['createdAt'] = undefined;
/**
 * @member {Date} updatedAt
 */
UsersPermissionsRole.prototype['updatedAt'] = undefined;




export default UsersPermissionsRolesGet200ResponseRolesInner;

