/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsUser from './UsersPermissionsUser';

/**
 * The UsersPermissionsUserRegistration model module.
 * @module model/UsersPermissionsUserRegistration
 * @version 1.0.0
 */
class UsersPermissionsUserRegistration {
    /**
     * Constructs a new <code>UsersPermissionsUserRegistration</code>.
     * @alias module:model/UsersPermissionsUserRegistration
     */
    constructor() { 
        
        UsersPermissionsUserRegistration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsUserRegistration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsUserRegistration} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsUserRegistration} The populated <code>UsersPermissionsUserRegistration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsUserRegistration();

            if (data.hasOwnProperty('jwt')) {
                obj['jwt'] = ApiClient.convertToType(data['jwt'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UsersPermissionsUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsUserRegistration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsUserRegistration</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['jwt'] && !(typeof data['jwt'] === 'string' || data['jwt'] instanceof String)) {
            throw new Error("Expected the field `jwt` to be a primitive type in the JSON string but got " + data['jwt']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          UsersPermissionsUser.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {String} jwt
 */
UsersPermissionsUserRegistration.prototype['jwt'] = undefined;

/**
 * @member {module:model/UsersPermissionsUser} user
 */
UsersPermissionsUserRegistration.prototype['user'] = undefined;






export default UsersPermissionsUserRegistration;

