/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsRole from './UsersPermissionsRole';
import UsersPermissionsUser from './UsersPermissionsUser';

/**
 * The UsersPost201Response model module.
 * @module model/UsersPost201Response
 * @version 1.0.0
 */
class UsersPost201Response {
    /**
     * Constructs a new <code>UsersPost201Response</code>.
     * @alias module:model/UsersPost201Response
     * @implements module:model/UsersPermissionsUser
     */
    constructor() { 
        UsersPermissionsUser.initialize(this);
        UsersPost201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPost201Response} obj Optional instance to populate.
     * @return {module:model/UsersPost201Response} The populated <code>UsersPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPost201Response();
            UsersPermissionsUser.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = UsersPermissionsRole.constructFromObject(data['role']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPost201Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // validate the optional field `role`
        if (data['role']) { // data not null
          UsersPermissionsRole.validateJSON(data['role']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
UsersPost201Response.prototype['id'] = undefined;

/**
 * @member {String} username
 */
UsersPost201Response.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UsersPost201Response.prototype['email'] = undefined;

/**
 * @member {String} provider
 */
UsersPost201Response.prototype['provider'] = undefined;

/**
 * @member {Boolean} confirmed
 */
UsersPost201Response.prototype['confirmed'] = undefined;

/**
 * @member {Boolean} blocked
 */
UsersPost201Response.prototype['blocked'] = undefined;

/**
 * @member {Date} createdAt
 */
UsersPost201Response.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
UsersPost201Response.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/UsersPermissionsRole} role
 */
UsersPost201Response.prototype['role'] = undefined;


// Implement UsersPermissionsUser interface:
/**
 * @member {Number} id
 */
UsersPermissionsUser.prototype['id'] = undefined;
/**
 * @member {String} username
 */
UsersPermissionsUser.prototype['username'] = undefined;
/**
 * @member {String} email
 */
UsersPermissionsUser.prototype['email'] = undefined;
/**
 * @member {String} provider
 */
UsersPermissionsUser.prototype['provider'] = undefined;
/**
 * @member {Boolean} confirmed
 */
UsersPermissionsUser.prototype['confirmed'] = undefined;
/**
 * @member {Boolean} blocked
 */
UsersPermissionsUser.prototype['blocked'] = undefined;
/**
 * @member {Date} createdAt
 */
UsersPermissionsUser.prototype['createdAt'] = undefined;
/**
 * @member {Date} updatedAt
 */
UsersPermissionsUser.prototype['updatedAt'] = undefined;




export default UsersPost201Response;

