/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsPermissionsTreeValue from './UsersPermissionsPermissionsTreeValue';

/**
 * The UsersPermissionsPermissionsGet200Response model module.
 * @module model/UsersPermissionsPermissionsGet200Response
 * @version 1.0.0
 */
class UsersPermissionsPermissionsGet200Response {
    /**
     * Constructs a new <code>UsersPermissionsPermissionsGet200Response</code>.
     * @alias module:model/UsersPermissionsPermissionsGet200Response
     */
    constructor() { 
        
        UsersPermissionsPermissionsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsPermissionsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsPermissionsGet200Response} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsPermissionsGet200Response} The populated <code>UsersPermissionsPermissionsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsPermissionsGet200Response();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': UsersPermissionsPermissionsTreeValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsPermissionsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsPermissionsGet200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object.<String, module:model/UsersPermissionsPermissionsTreeValue>} permissions
 */
UsersPermissionsPermissionsGet200Response.prototype['permissions'] = undefined;






export default UsersPermissionsPermissionsGet200Response;

