/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsPermissionsTreeValueControllersValueValue from './UsersPermissionsPermissionsTreeValueControllersValueValue';

/**
 * The UsersPermissionsPermissionsTreeValue model module.
 * @module model/UsersPermissionsPermissionsTreeValue
 * @version 1.0.0
 */
class UsersPermissionsPermissionsTreeValue {
    /**
     * Constructs a new <code>UsersPermissionsPermissionsTreeValue</code>.
     * every api
     * @alias module:model/UsersPermissionsPermissionsTreeValue
     */
    constructor() { 
        
        UsersPermissionsPermissionsTreeValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsPermissionsTreeValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsPermissionsTreeValue} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsPermissionsTreeValue} The populated <code>UsersPermissionsPermissionsTreeValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsPermissionsTreeValue();

            if (data.hasOwnProperty('controllers')) {
                obj['controllers'] = ApiClient.convertToType(data['controllers'], {'String': {'String': UsersPermissionsPermissionsTreeValueControllersValueValue}});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsPermissionsTreeValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsPermissionsTreeValue</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * every controller of the api
 * @member {Object.<String, Object.<String, module:model/UsersPermissionsPermissionsTreeValueControllersValueValue>>} controllers
 */
UsersPermissionsPermissionsTreeValue.prototype['controllers'] = undefined;






export default UsersPermissionsPermissionsTreeValue;

