/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsRolesGet200ResponseRolesInner from './UsersPermissionsRolesGet200ResponseRolesInner';

/**
 * The UsersPermissionsRolesGet200Response model module.
 * @module model/UsersPermissionsRolesGet200Response
 * @version 1.0.0
 */
class UsersPermissionsRolesGet200Response {
    /**
     * Constructs a new <code>UsersPermissionsRolesGet200Response</code>.
     * @alias module:model/UsersPermissionsRolesGet200Response
     */
    constructor() { 
        
        UsersPermissionsRolesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsRolesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsRolesGet200Response} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsRolesGet200Response} The populated <code>UsersPermissionsRolesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsRolesGet200Response();

            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [UsersPermissionsRolesGet200ResponseRolesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsRolesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsRolesGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['roles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['roles'])) {
                throw new Error("Expected the field `roles` to be an array in the JSON data but got " + data['roles']);
            }
            // validate the optional field `roles` (array)
            for (const item of data['roles']) {
                UsersPermissionsRolesGet200ResponseRolesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/UsersPermissionsRolesGet200ResponseRolesInner>} roles
 */
UsersPermissionsRolesGet200Response.prototype['roles'] = undefined;






export default UsersPermissionsRolesGet200Response;

