/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsPermissionsTreeValue from './UsersPermissionsPermissionsTreeValue';

/**
 * The UsersPermissionsRolesPostRequest model module.
 * @module model/UsersPermissionsRolesPostRequest
 * @version 1.0.0
 */
class UsersPermissionsRolesPostRequest {
    /**
     * Constructs a new <code>UsersPermissionsRolesPostRequest</code>.
     * @alias module:model/UsersPermissionsRolesPostRequest
     */
    constructor() { 
        
        UsersPermissionsRolesPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsRolesPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsRolesPostRequest} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsRolesPostRequest} The populated <code>UsersPermissionsRolesPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsRolesPostRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': UsersPermissionsPermissionsTreeValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsRolesPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsRolesPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
UsersPermissionsRolesPostRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UsersPermissionsRolesPostRequest.prototype['description'] = undefined;

/**
 * @member {String} type
 */
UsersPermissionsRolesPostRequest.prototype['type'] = undefined;

/**
 * @member {Object.<String, module:model/UsersPermissionsPermissionsTreeValue>} permissions
 */
UsersPermissionsRolesPostRequest.prototype['permissions'] = undefined;






export default UsersPermissionsRolesPostRequest;

