/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersPermissionsRole from './UsersPermissionsRole';

/**
 * The UsersPermissionsRolesIdGet200Response model module.
 * @module model/UsersPermissionsRolesIdGet200Response
 * @version 1.0.0
 */
class UsersPermissionsRolesIdGet200Response {
    /**
     * Constructs a new <code>UsersPermissionsRolesIdGet200Response</code>.
     * @alias module:model/UsersPermissionsRolesIdGet200Response
     */
    constructor() { 
        
        UsersPermissionsRolesIdGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsRolesIdGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsRolesIdGet200Response} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsRolesIdGet200Response} The populated <code>UsersPermissionsRolesIdGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsRolesIdGet200Response();

            if (data.hasOwnProperty('role')) {
                obj['role'] = UsersPermissionsRole.constructFromObject(data['role']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsRolesIdGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsRolesIdGet200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `role`
        if (data['role']) { // data not null
          UsersPermissionsRole.validateJSON(data['role']);
        }

        return true;
    }


}



/**
 * @member {module:model/UsersPermissionsRole} role
 */
UsersPermissionsRolesIdGet200Response.prototype['role'] = undefined;






export default UsersPermissionsRolesIdGet200Response;

