/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersPermissionsPermissionsTreeValueControllersValueValue model module.
 * @module model/UsersPermissionsPermissionsTreeValueControllersValueValue
 * @version 1.0.0
 */
class UsersPermissionsPermissionsTreeValueControllersValueValue {
    /**
     * Constructs a new <code>UsersPermissionsPermissionsTreeValueControllersValueValue</code>.
     * every action of every controller
     * @alias module:model/UsersPermissionsPermissionsTreeValueControllersValueValue
     */
    constructor() { 
        
        UsersPermissionsPermissionsTreeValueControllersValueValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPermissionsPermissionsTreeValueControllersValueValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPermissionsPermissionsTreeValueControllersValueValue} obj Optional instance to populate.
     * @return {module:model/UsersPermissionsPermissionsTreeValueControllersValueValue} The populated <code>UsersPermissionsPermissionsTreeValueControllersValueValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPermissionsPermissionsTreeValueControllersValueValue();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersPermissionsPermissionsTreeValueControllersValueValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersPermissionsPermissionsTreeValueControllersValueValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['policy'] && !(typeof data['policy'] === 'string' || data['policy'] instanceof String)) {
            throw new Error("Expected the field `policy` to be a primitive type in the JSON string but got " + data['policy']);
        }

        return true;
    }


}



/**
 * @member {Boolean} enabled
 */
UsersPermissionsPermissionsTreeValueControllersValueValue.prototype['enabled'] = undefined;

/**
 * @member {String} policy
 */
UsersPermissionsPermissionsTreeValueControllersValueValue.prototype['policy'] = undefined;






export default UsersPermissionsPermissionsTreeValueControllersValueValue;

