/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthChangePasswordPostRequest from './model/AuthChangePasswordPostRequest';
import AuthForgotPasswordPost200Response from './model/AuthForgotPasswordPost200Response';
import AuthForgotPasswordPostRequest from './model/AuthForgotPasswordPostRequest';
import AuthLocalPostRequest from './model/AuthLocalPostRequest';
import AuthLocalRegisterPostRequest from './model/AuthLocalRegisterPostRequest';
import AuthResetPasswordPostRequest from './model/AuthResetPasswordPostRequest';
import AuthSendEmailConfirmationPost200Response from './model/AuthSendEmailConfirmationPost200Response';
import Error from './model/Error';
import ErrorData from './model/ErrorData';
import ErrorError from './model/ErrorError';
import Todo from './model/Todo';
import TodoCreatedBy from './model/TodoCreatedBy';
import TodoCreatedByData from './model/TodoCreatedByData';
import TodoCreatedByDataAttributes from './model/TodoCreatedByDataAttributes';
import TodoCreatedByDataAttributesRoles from './model/TodoCreatedByDataAttributesRoles';
import TodoCreatedByDataAttributesRolesDataInner from './model/TodoCreatedByDataAttributesRolesDataInner';
import TodoCreatedByDataAttributesRolesDataInnerAttributes from './model/TodoCreatedByDataAttributesRolesDataInnerAttributes';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes';
import TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';
import TodoCreatedByDataAttributesRolesDataInnerAttributesUsers from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsers';
import TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner from './model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner';
import TodoListResponse from './model/TodoListResponse';
import TodoListResponseDataItem from './model/TodoListResponseDataItem';
import TodoListResponseMeta from './model/TodoListResponseMeta';
import TodoListResponseMetaPagination from './model/TodoListResponseMetaPagination';
import TodoRequest from './model/TodoRequest';
import TodoRequestData from './model/TodoRequestData';
import TodoResponse from './model/TodoResponse';
import TodoResponseDataObject from './model/TodoResponseDataObject';
import UploadFile from './model/UploadFile';
import UploadIdPostRequestFileInfo from './model/UploadIdPostRequestFileInfo';
import UsersPermissionsPermissionsGet200Response from './model/UsersPermissionsPermissionsGet200Response';
import UsersPermissionsPermissionsTreeValue from './model/UsersPermissionsPermissionsTreeValue';
import UsersPermissionsPermissionsTreeValueControllersValueValue from './model/UsersPermissionsPermissionsTreeValueControllersValueValue';
import UsersPermissionsRole from './model/UsersPermissionsRole';
import UsersPermissionsRolesGet200Response from './model/UsersPermissionsRolesGet200Response';
import UsersPermissionsRolesGet200ResponseRolesInner from './model/UsersPermissionsRolesGet200ResponseRolesInner';
import UsersPermissionsRolesIdGet200Response from './model/UsersPermissionsRolesIdGet200Response';
import UsersPermissionsRolesPostRequest from './model/UsersPermissionsRolesPostRequest';
import UsersPermissionsUser from './model/UsersPermissionsUser';
import UsersPermissionsUserRegistration from './model/UsersPermissionsUserRegistration';
import UsersPost201Response from './model/UsersPost201Response';
import UsersPostRequest from './model/UsersPostRequest';
import TodoApi from './api/TodoApi';
import UploadFileApi from './api/UploadFileApi';
import UsersPermissionsAuthApi from './api/UsersPermissionsAuthApi';
import UsersPermissionsUsersRolesApi from './api/UsersPermissionsUsersRolesApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Documentation = require('index'); // See note below*.
* var xxxSvc = new Documentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Documentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Documentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Documentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthChangePasswordPostRequest model constructor.
     * @property {module:model/AuthChangePasswordPostRequest}
     */
    AuthChangePasswordPostRequest,

    /**
     * The AuthForgotPasswordPost200Response model constructor.
     * @property {module:model/AuthForgotPasswordPost200Response}
     */
    AuthForgotPasswordPost200Response,

    /**
     * The AuthForgotPasswordPostRequest model constructor.
     * @property {module:model/AuthForgotPasswordPostRequest}
     */
    AuthForgotPasswordPostRequest,

    /**
     * The AuthLocalPostRequest model constructor.
     * @property {module:model/AuthLocalPostRequest}
     */
    AuthLocalPostRequest,

    /**
     * The AuthLocalRegisterPostRequest model constructor.
     * @property {module:model/AuthLocalRegisterPostRequest}
     */
    AuthLocalRegisterPostRequest,

    /**
     * The AuthResetPasswordPostRequest model constructor.
     * @property {module:model/AuthResetPasswordPostRequest}
     */
    AuthResetPasswordPostRequest,

    /**
     * The AuthSendEmailConfirmationPost200Response model constructor.
     * @property {module:model/AuthSendEmailConfirmationPost200Response}
     */
    AuthSendEmailConfirmationPost200Response,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorData model constructor.
     * @property {module:model/ErrorData}
     */
    ErrorData,

    /**
     * The ErrorError model constructor.
     * @property {module:model/ErrorError}
     */
    ErrorError,

    /**
     * The Todo model constructor.
     * @property {module:model/Todo}
     */
    Todo,

    /**
     * The TodoCreatedBy model constructor.
     * @property {module:model/TodoCreatedBy}
     */
    TodoCreatedBy,

    /**
     * The TodoCreatedByData model constructor.
     * @property {module:model/TodoCreatedByData}
     */
    TodoCreatedByData,

    /**
     * The TodoCreatedByDataAttributes model constructor.
     * @property {module:model/TodoCreatedByDataAttributes}
     */
    TodoCreatedByDataAttributes,

    /**
     * The TodoCreatedByDataAttributesRoles model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRoles}
     */
    TodoCreatedByDataAttributesRoles,

    /**
     * The TodoCreatedByDataAttributesRolesDataInner model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInner}
     */
    TodoCreatedByDataAttributesRolesDataInner,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributes model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributes}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributes,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesPermissions,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInner,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesUsers model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsers}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesUsers,

    /**
     * The TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner model constructor.
     * @property {module:model/TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner}
     */
    TodoCreatedByDataAttributesRolesDataInnerAttributesUsersDataInner,

    /**
     * The TodoListResponse model constructor.
     * @property {module:model/TodoListResponse}
     */
    TodoListResponse,

    /**
     * The TodoListResponseDataItem model constructor.
     * @property {module:model/TodoListResponseDataItem}
     */
    TodoListResponseDataItem,

    /**
     * The TodoListResponseMeta model constructor.
     * @property {module:model/TodoListResponseMeta}
     */
    TodoListResponseMeta,

    /**
     * The TodoListResponseMetaPagination model constructor.
     * @property {module:model/TodoListResponseMetaPagination}
     */
    TodoListResponseMetaPagination,

    /**
     * The TodoRequest model constructor.
     * @property {module:model/TodoRequest}
     */
    TodoRequest,

    /**
     * The TodoRequestData model constructor.
     * @property {module:model/TodoRequestData}
     */
    TodoRequestData,

    /**
     * The TodoResponse model constructor.
     * @property {module:model/TodoResponse}
     */
    TodoResponse,

    /**
     * The TodoResponseDataObject model constructor.
     * @property {module:model/TodoResponseDataObject}
     */
    TodoResponseDataObject,

    /**
     * The UploadFile model constructor.
     * @property {module:model/UploadFile}
     */
    UploadFile,

    /**
     * The UploadIdPostRequestFileInfo model constructor.
     * @property {module:model/UploadIdPostRequestFileInfo}
     */
    UploadIdPostRequestFileInfo,

    /**
     * The UsersPermissionsPermissionsGet200Response model constructor.
     * @property {module:model/UsersPermissionsPermissionsGet200Response}
     */
    UsersPermissionsPermissionsGet200Response,

    /**
     * The UsersPermissionsPermissionsTreeValue model constructor.
     * @property {module:model/UsersPermissionsPermissionsTreeValue}
     */
    UsersPermissionsPermissionsTreeValue,

    /**
     * The UsersPermissionsPermissionsTreeValueControllersValueValue model constructor.
     * @property {module:model/UsersPermissionsPermissionsTreeValueControllersValueValue}
     */
    UsersPermissionsPermissionsTreeValueControllersValueValue,

    /**
     * The UsersPermissionsRole model constructor.
     * @property {module:model/UsersPermissionsRole}
     */
    UsersPermissionsRole,

    /**
     * The UsersPermissionsRolesGet200Response model constructor.
     * @property {module:model/UsersPermissionsRolesGet200Response}
     */
    UsersPermissionsRolesGet200Response,

    /**
     * The UsersPermissionsRolesGet200ResponseRolesInner model constructor.
     * @property {module:model/UsersPermissionsRolesGet200ResponseRolesInner}
     */
    UsersPermissionsRolesGet200ResponseRolesInner,

    /**
     * The UsersPermissionsRolesIdGet200Response model constructor.
     * @property {module:model/UsersPermissionsRolesIdGet200Response}
     */
    UsersPermissionsRolesIdGet200Response,

    /**
     * The UsersPermissionsRolesPostRequest model constructor.
     * @property {module:model/UsersPermissionsRolesPostRequest}
     */
    UsersPermissionsRolesPostRequest,

    /**
     * The UsersPermissionsUser model constructor.
     * @property {module:model/UsersPermissionsUser}
     */
    UsersPermissionsUser,

    /**
     * The UsersPermissionsUserRegistration model constructor.
     * @property {module:model/UsersPermissionsUserRegistration}
     */
    UsersPermissionsUserRegistration,

    /**
     * The UsersPost201Response model constructor.
     * @property {module:model/UsersPost201Response}
     */
    UsersPost201Response,

    /**
     * The UsersPostRequest model constructor.
     * @property {module:model/UsersPostRequest}
     */
    UsersPostRequest,

    /**
    * The TodoApi service constructor.
    * @property {module:api/TodoApi}
    */
    TodoApi,

    /**
    * The UploadFileApi service constructor.
    * @property {module:api/UploadFileApi}
    */
    UploadFileApi,

    /**
    * The UsersPermissionsAuthApi service constructor.
    * @property {module:api/UsersPermissionsAuthApi}
    */
    UsersPermissionsAuthApi,

    /**
    * The UsersPermissionsUsersRolesApi service constructor.
    * @property {module:api/UsersPermissionsUsersRolesApi}
    */
    UsersPermissionsUsersRolesApi
};
