/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.UploadFileApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UploadFileApi', function() {
    describe('uploadFilesGet', function() {
      it('should call uploadFilesGet successfully', function(done) {
        //uncomment below and update the code to test uploadFilesGet
        //instance.uploadFilesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadFilesIdDelete', function() {
      it('should call uploadFilesIdDelete successfully', function(done) {
        //uncomment below and update the code to test uploadFilesIdDelete
        //instance.uploadFilesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadFilesIdGet', function() {
      it('should call uploadFilesIdGet successfully', function(done) {
        //uncomment below and update the code to test uploadFilesIdGet
        //instance.uploadFilesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadIdPost', function() {
      it('should call uploadIdPost successfully', function(done) {
        //uncomment below and update the code to test uploadIdPost
        //instance.uploadIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadPost', function() {
      it('should call uploadPost successfully', function(done) {
        //uncomment below and update the code to test uploadPost
        //instance.uploadPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
