/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Documentation);
  }
}(this, function(expect, Documentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Documentation.UsersPermissionsAuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersPermissionsAuthApi', function() {
    describe('authChangePasswordPost', function() {
      it('should call authChangePasswordPost successfully', function(done) {
        //uncomment below and update the code to test authChangePasswordPost
        //instance.authChangePasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authEmailConfirmationGet', function() {
      it('should call authEmailConfirmationGet successfully', function(done) {
        //uncomment below and update the code to test authEmailConfirmationGet
        //instance.authEmailConfirmationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authForgotPasswordPost', function() {
      it('should call authForgotPasswordPost successfully', function(done) {
        //uncomment below and update the code to test authForgotPasswordPost
        //instance.authForgotPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authLocalPost', function() {
      it('should call authLocalPost successfully', function(done) {
        //uncomment below and update the code to test authLocalPost
        //instance.authLocalPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authLocalRegisterPost', function() {
      it('should call authLocalRegisterPost successfully', function(done) {
        //uncomment below and update the code to test authLocalRegisterPost
        //instance.authLocalRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authProviderCallbackGet', function() {
      it('should call authProviderCallbackGet successfully', function(done) {
        //uncomment below and update the code to test authProviderCallbackGet
        //instance.authProviderCallbackGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authResetPasswordPost', function() {
      it('should call authResetPasswordPost successfully', function(done) {
        //uncomment below and update the code to test authResetPasswordPost
        //instance.authResetPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authSendEmailConfirmationPost', function() {
      it('should call authSendEmailConfirmationPost successfully', function(done) {
        //uncomment below and update the code to test authSendEmailConfirmationPost
        //instance.authSendEmailConfirmationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('connectProviderGet', function() {
      it('should call connectProviderGet successfully', function(done) {
        //uncomment below and update the code to test connectProviderGet
        //instance.connectProviderGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
